<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>Shinobi.Fuda.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Shinobi.Fuda\Shinobi.Fuda.csproj" />
    <ProjectReference Include="..\..\samples\Shinobi.Fuda.Samples\Shinobi.Fuda.Samples.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\samples\Shinobi.Fuda.Samples\templates\invoice-template.docx" Link="templates\invoice-template.docx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
